name: newsly
description: A modern Flutter news reading app with GetX

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Navigation
  get: ^4.6.6
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  
  # HTTP & API
  dio: ^5.4.0
  
  # Local Storage
  get_storage: ^2.1.1
  
  # UI
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  
  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # assets:
    # - assets/images/
    # - assets/icons/
