// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7kdpBzqdZopLIEPWHYHC9FgYZ7SMEEoQ',
    appId: '1:861845318269:web:37a42c6fed5f8528989f14',
    messagingSenderId: '861845318269',
    projectId: 'newsly-90dbd',
    authDomain: 'newsly-90dbd.firebaseapp.com',
    storageBucket: 'newsly-90dbd.firebasestorage.app',
    measurementId: 'G-X9B6RZLJL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXm-KIMuhWDbw2Lc2uiRcBQODoa_J3I3I',
    appId: '1:861845318269:android:06ff652c655401bd989f14',
    messagingSenderId: '861845318269',
    projectId: 'newsly-90dbd',
    storageBucket: 'newsly-90dbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA5rIGqjP4MGvQ4gfcVCgjbmqBmcXHY8Q',
    appId: '1:861845318269:ios:ab7ed6e035cb6e78989f14',
    messagingSenderId: '861845318269',
    projectId: 'newsly-90dbd',
    storageBucket: 'newsly-90dbd.firebasestorage.app',
    iosClientId: '861845318269-tugekc9njt102318loaglmipobeh64t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA5rIGqjP4MGvQ4gfcVCgjbmqBmcXHY8Q',
    appId: '1:861845318269:ios:ab7ed6e035cb6e78989f14',
    messagingSenderId: '861845318269',
    projectId: 'newsly-90dbd',
    storageBucket: 'newsly-90dbd.firebasestorage.app',
    iosClientId: '861845318269-tugekc9njt102318loaglmipobeh64t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7kdpBzqdZopLIEPWHYHC9FgYZ7SMEEoQ',
    appId: '1:861845318269:web:81740da2e840dbe0989f14',
    messagingSenderId: '861845318269',
    projectId: 'newsly-90dbd',
    authDomain: 'newsly-90dbd.firebaseapp.com',
    storageBucket: 'newsly-90dbd.firebasestorage.app',
    measurementId: 'G-9ZHMDSPFVV',
  );

}